# Generated by Django 5.1 on 2024-08-16 18:28

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.game_preview_directory_path),
        ),
    ]
