# Generated by Django 5.1 on 2024-08-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_order_receipt_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='games',
        ),
    ]
